<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ec2ceea3-99de-4a12-a3b7-7ffd15b5afa8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Exceptions.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="MinimalHelpers.OpenApi" Version="2.1.21" />
    <PackageReference Include="MinimalHelpers.Routing.Analyzers" Version="1.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    <PackageReference Include="TinyHelpers" Version="3.3.20" />
    <PackageReference Include="TinyHelpers.AspNetCore" Version="4.1.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyToolbox.BusinessLayer\MyToolbox.BusinessLayer.csproj" />
  </ItemGroup>

</Project>
